name: 'Salad Container Engine Action'
description:
  'Automatically deploy updated container images to your Salad Account.'
author: 'SaladTechnologies'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'cloud-snow'
  color: 'green'

# Define your inputs here.
inputs:
  salad_organization:
    description: 'Your Salad organization name.'
    required: true

  salad_project:
    description: 'Your Salad project name.'
    required: true

  salad_container_group:
    description: 'Your Salad container group name.'
    required: true

  salad_api_key:
    description: 'Your Salad API key'
    required: true

  image_name:
    description: 'The name of the container, including the registry and the tag'
    required: true

  # # ghcr
  # github_token:
  #   description:
  #     'Personal Access Token (PAT) used to authenticate with the GitHub
  #     Container Registry.'
  #   required: false

  # # basic auth
  # basic_username:
  #   description:
  #     'The username for basic auth - to be used in conjunction with
  #     `basic_password`'
  #   required: false

  # basic_password:
  #   description:
  #     'The password for basic auth - to be used in conjunction with
  #     `basic_username`'
  #   required: false

  # # gcp gcr
  # service_key:
  #   description:
  #     'The username for basic auth - to be used in conjunction with
  #     `basic_password`'
  #   required: false

  # # ecr
  # aws_access_key_id:
  #   description:
  #     'AWS Access Key ID - to be used in conjunction with
  #     `aws_secret_access_key`'
  #   required: false

  # aws_secret_access_key:
  #   description:
  #     'AWS Secret Access Key - to be used in conjunction with
  #     `aws_access_key_id`'
  #   required: false

  # # docker hub
  # dockerhub_username:
  #   description: 'Docker Hub Username'
  #   required: false

  # dockerhub_password:
  #   description: 'Docker Hub Personal Access Token'
  #   required: false

runs:
  using: node20
  main: dist/index.js
