name: 'Salad Container Engine Action'
description: 'Automatically deploy new GHCR containers to your Salad Account.'
author: 'SaladTechnologies'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'cloud-snow'
  color: 'green'

# Define your inputs here.
inputs:
  salad-organization:
    description: 'Your Salad organization name.'
    required: true
  salad-project:
    description: 'Your Salad project name.'
    required: true
  salad-container-group:
    description: 'Your Salad container group name.'
    required: true

# # Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
